apiVersion: batch/v2
kind: CronJob
metadata:
  name: hello-cronjob-second
  namespace: default
spec:
  schedule: "*/5 * * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello-second
              image: busybox
              args:
                - /bin/sh
                - -c
                - echo "Hello scond from CronJob at $(date)"
          restartPolicy: OnFailure
